###########################################################################
#
#     基础配置
#
# ##########################################################################

[project]
nav = [
  {"Home" = [
      "index.md",
      {"快速入门" = [
          {"article1" = "article1.md"},
          {"article2" = "article2.md"}
      ]}
  ]},
  "markdown.md"
]

extra_css = [
    "css/content.css",
    "css/article.css"
]

extra_js = [
    "js/mathjax.js"
]


# 主题变体：
#   - modern (默认)
#   - classic
# variant = "modern"

# 必需
# site_name：提供了网站名称。该名称将包含在 HTML 头部和页面标题中。
site_name = "稷下学宫"

# 可选
# site_url：指定了网站的规范 URL。该 URL 会出现在 HTML 头部中，除非你正在为离线使用构建网站，否则应进行设置。
# site_url = ""

# 可选
# site_description：提供了网站的描述。该描述将包含在 HTML 头部中。部分搜索引擎会使用此描述来概括页面内容。
# site_description = ""

# 可选
# site_author：提供了网站的作者。该作者将包含在 HTML 头部中。
site_author = "Air"

repo_url = "https://github.com/LinXinJi/AirHub"
repo_name = "AirHub"

# 可选
# copyright：提供了网站的版权信息。该信息将包含在 HTML 头部中。
copyright = """
Copyright &copy; 2026 XinJi Lin
"""

# 可选
# dev_addr：指定了开发服务器的地址和端口。默认值为 "localhost:8000"。
# dev_addr = "localhost:8000"

# 可选
# docs_dir：指定了文档目录的路径。默认值为 "docs"。
# docs_dir = "docs"

# 可选
# site_dir：指定了网站输出目录的路径。默认值为 "site"。
# site_dir = "site"

# 可选
# use_directory_urls：设置控制文档网站的目录结构，从而映像用于链接页面的 URL 格式。
#
# 请注意：
#   - 默认值为 true。
#   - 在为离线使用构建时，此选项会自动设置为 false，这样您的文档便可在没有网络服务器的本地文件系统中浏览。
# use_directory_urls = false

# 可选
# watch：额外监控的文件。每个条目都是一个相对于配置文件所在目录解析的字符串。
# watch = []

[project.extra]
# 主页连接
# homepage = "https://"
# 生成器声明
generator = true

[project.extra.tags]
HTML5 = "html"
JavaScript = "js"


# 社交链接
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/LinXinJi"

#######################################################
#
#    主题配置
#
#######################################################

[project.theme]
# logo = "images/logo.png"

# 站点图标
# favicon = "images/favicon.png"

# 全局功能
features = [
    "header.autohide",              # 自动隐藏页眉
    "navigation.tabs",              # 导航栏标签
    "navigation.tabs.sticky",       # 导航栏标签黏住页眉
    "navigation.sections",          # 导航栏分区
    "navigation.indexes",           # 章节索引页面
    "navigation.footer",            # 页脚导航（上一页、下一页）
    "navigation.instant",           # 导航栏即时更新
    "navigation.instant.progress",  # 导航栏即时更新进度条
    "navigation.tracking",          # 锚点追踪
    "toc.follow",                   # 目录跟随滚动
    "search.highlight",             # 搜索结果高亮

]

[project.theme.icon]
# logo = "lucide/smile"
repo = "fontawesome/brands/git-alt"
previous = "fontawesome/solid/angle-left"
next = "fontawesome/solid/angle-right"

[project.theme.icon.tag]
default = "lucide/hash"
html = "fontawesome/brands/html5"
js = "fontawesome/brands/js"


[[project.theme.palette]]
# 主题方案：default(浅色)
scheme = "default"
# 主色
primary = "deep purple"
# 强调色
accent = "green"
# 切换按钮图标
toggle.icon = "lucide/sun"


[[project.theme.palette]]
# 主题方案：slate(深色)
scheme = "slate"
# 主色
primary = "pink"
# 强调色
accent = "light green"
# 切换按钮图标
toggle.icon = "lucide/moon"


[project.theme.font]
# 文本字体
text = "Aa古典刻本宋油墨版"
# 等宽字体
code = "Maple Mono NF CN"

#########################################################
# 
#    插件
# 
#########################################################


[project.plugins.offline]
enabled = true

#########################################################
# 
#    markdown 扩展
# 
########################################################
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]

